# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-multiple-languages-plugin
- jekyll-spaceship

# Site settings
url: 'https://juantoca.github.io'
baseurl: ''
title: 'Juan Toca'
description: 'This is my new website'
permalink: pretty
logo: "/assets/profile_pic.png"

# Pagination
paginate: 5
paginate_path: /blog/page:num/

# Header nav
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
  null

# Collections
collections:
  posts:
    title: Posts
    output: true

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

languages: ["en", "es"]

jekyll-spaceship:
  mermaid-processor:
    src: https://mermaid.ink/img/
